package com.cbmu.covidmap;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Date;

@Slf4j
@Controller // This means that this class is a Controller
@RequestMapping(path="/cali-counts") // This means URL's start with /demo (after Application path)
public class CaliHistoricalFacilityCountsController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CaliHistoricalFacilityCountsRepository caliHistoricalFacilityCountsRepository;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<CaliHistoricalFacilityCounts> getAllNationalCounts() {
        // This returns a JSON or XML with the users
        return caliHistoricalFacilityCountsRepository.findAll();
    }

    @GetMapping(path = "/date/{date}")
    public @ResponseBody Iterable<CaliHistoricalFacilityCounts> getAllByDate(
            @DateTimeFormat(pattern = "yyyy-MM-dd'T'hh:mm:ssZ") @PathVariable Date date) {

        log.info("Searching for all records on {}", date);
        return caliHistoricalFacilityCountsRepository.findAllByDate(date);
    }
}
