package com.cbmu.covidmap;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Date;


@Controller // This means that this class is a Controller
@RequestMapping(path="/national-counts") // This means URL's start with /demo (after Application path)
public class NationalCountsController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NationalCountsRepository nationalCountsRepository;

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<NationalCounts> getAllNationalCounts() {
        // This returns a JSON or XML with the users
        return nationalCountsRepository.findAll();
    }

    @GetMapping(path = "/date/{date}")
    public @ResponseBody Iterable<NationalCounts> getAllByDate(@PathVariable Date date) {
        return nationalCountsRepository.findAllByDate(date);
    }


}
